Repository AdministratorNei/nei-almoxarifado-api, pull requests merged in 2024-02, with the labels that each got.

#20 andriel/refactor_dto_name
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemResponseDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/ItemMapper.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
Labels: enhancement

#21 andriel/items_services_tests
  src/test/java/com/ufrn/nei/almoxarifadoapi/service/ItemServiceTest.java
Labels: test

#24 Rodrigo/docs: Criação da documentação dos endpoints do controller Item
  pom.xml
  src/main/java/com/ufrn/nei/almoxarifadoapi/config/SpringDocsOpenApiConfig.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
  src/main/resources/application.properties
Labels: documentation

#25 Rodrig/refactor: Refatoração do código do método delete e Adicionar lançamento de erro
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/exception/ItemNotActiveException.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
Labels: enhancement

#27 Rodrigo/feat: Criação da estrutra básica para a entidade usuário
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/UserController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/UserMapper.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/user/UserCreateDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/user/UserPasswordUpdateDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/user/UserResponseDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/exception/PasswordInvalidException.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/repository/UserRepository.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
Labels: enhancement

#30 rodrigo/feat: Criação da estrutura para o controller relacionado as operações
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/OperationController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/RecordController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemDeleteDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemRecordDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/RecordMapper.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/UserMapper.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/record/RecordCreateDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/record/RecordCreateItemDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/record/RecordResponseDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/user/UserRecordDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/entity/ItemEntity.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/entity/RecordEntity.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/enums/RecordOperationEnum.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/exception/OperationErrorException.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/infra/RestExceptionHandler.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/repository/RecordRepository.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/OperationService.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/RecordService.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/UserService.java
  src/main/resources/db/migration/V6__RecordNewColumns.sql
  src/test/java/com/ufrn/nei/almoxarifadoapi/service/ItemServiceTest.java
Labels: enhancement
