Repository AdministratorNei/nei-almoxarifado-api, pull requests merged in 2024-01, with the labels that each got.

#11 Rodrigo/test: Criação de testes para o Service da entidade Role
  src/test/java/com/ufrn/nei/almoxarifadoapi/controller/RoleControllerTest.java
  src/test/java/com/ufrn/nei/almoxarifadoapi/service/RoleServiceTest.java
  src/test/resources/application-test.properties
Labels: test

#14 andriel/items operations
  src/main/java/com/ufrn/nei/almoxarifadoapi/controller/ItemController.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemCreateDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemDetailsDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/item/ItemUpdateDTO.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/dto/mapper/ItemMapper.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/repository/ItemRepository.java
  src/main/java/com/ufrn/nei/almoxarifadoapi/service/ItemService.java
Labels: enhancement

#15 Rodrigo/docs: Adicionando template para pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
